version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=frameworkless
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  mazeroute:
    container_name: mazeroute-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db